# Generated by Django 5.2 on 2025-04-12 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_file_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 17, 30, 45, 814039, tzinfo=datetime.timezone.utc)),
        ),
    ]
