# Generated by Django 5.2 on 2025-04-12 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 17, 44, 8, 111410, tzinfo=datetime.timezone.utc)),
        ),
    ]
